### ISSUE TITLE
Dump for all commands

### ISSUE THREAD

**Issue by alex-sever-h** [tuxedo0801/Arduino-Hob2Hood#2]
First of all,  thank you for sharing your findings.
Second, I am trying right now to make the opposite of your device. My hood is hob2hood compliant, but my burner is not.
I have an IR blaster I previously used with my A/C and tried to send the codes in your project to the hood.
However, nothing happens.

My guess is that either:
1. the protocol is something custom (I've tried all of them), and just the hash is recorded in your code (likely)
2. H2H requires some special startup enabling code (unlikely)

Could you please run a raw IR data dumper like this one, and share the results with us?
https://github.com/z3t0/Arduino-IRremote/blob/master/examples/IRreceiveDumpV2/IRreceiveDumpV2.ino

**Comment by tuxedo0801** [comment]
just search github for "hob2hood", let's you find this:

https://github.com/JameZUK/hob2hood-RAW-IR-Codes

**Comment by alex-sever-h** [comment]
Thank you. 
I tried searching all day, but I found just the receiving codes.
Tested the raw IR send on my hood, and works perfectly.

**Comment by xuio** [comment]
@alex-sever-h can you share your code and setup? thanks!
