### ISSUE TITLE
How to send?

### ISSUE THREAD

**Issue by xuio** [tuxedo0801/Arduino-Hob2Hood#3]
First of all, huge thanks for documenting this!

I personally want to solve the opposite problem: switch off my hood with a "smart home" button.

I am using a Teensy 4.0 and tried sending the codes in all different encodings without success. I also tried the raw dumps  from here: https://github.com/JameZUK/hob2hood-RAW-IR-Codes

Can someone shine some light on this? HAs anyone tried this before and can suggest a setup that works?

**Comment by cernst11** [comment]
Hey @xuio I ran into the same issue  this gist should do the trick for you. 
https://gist.github.com/cernst11/8fb0d45bbae6af52da6aae25baa94aa6 
Once it's in a polished state I will have it in its own repo.
